[package]
name = "nhdl"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.12.0"
textwrap = "0.14.2"
tokio = { version = "1.12.0", features = ["full"] }
toml = "0.5"
